export const TOGGLEFILTER = "TOGGLEFILTER";
export const HANDLEFILTERCHANGE = "HANDLEFILTERCHANGE";
export const FETCHPROPERTIES = "FETCHPROPERTIES";
export const VIEWSUMMARY = 'VIEWSUMMARY';
export const CLOSEMODAL = 'CLOSEMODAL';
