export const TOGGLEFILTER = "TOGGLEFILTER";
export const HANDLEFILTERCHANGE = "HANDLEFILTERCHANGE";
export const FETCHPROPERTIES = "FETCHPROPERTIES";
export const VIEWSUMMARY = 'VIEWSUMMARY';
export const CLOSEMODAL = 'CLOSEMODAL';

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const ATTEMPTLOGIN = "ATTEMPTLOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

// === MAX's AUTH ACTIONS ====//
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
